### ISSUE TITLE
Xamarin.Forms.Nuke does not honor resolutions

### ISSUE THREAD

**Issue by acuntex** [roubachof/Xamarin.Forms.Nuke#11] opened 2020-08-18 15:09 UTC
I just wanted to try to switch from FFImageLoading to Xamarin.Forms.Nuke.

All my image assets in the app are in 3 resolutions, e.g. icon_add.png, icon_add@2x.png and icon_add@3x.png.

Unfortunately Xamarin.Forms.Nuke does not load the correct image in the right resolution for the specific ios device but always the smallest one.

**Comment by roubachof** [comment] 2020-08-18 15:15
see if this PR could fix this: https://github.com/roubachof/Xamarin.Forms.Nuke/pull/5/commits/38bc32990f9bbc8c394dcccd272e103be6ced7cc

**Comment by acuntex** [comment] 2020-08-18 15:43
Unfortunately no.

fileUrl is not null because in Xamarin.IOS you can also put the various resolutions in the Resources folder, you don't have to put it in an imageset.

NSBundle.MainBundle.GetUrlForResource does return a valid file but it's the wrong file.

**Comment by roubachof** [comment] 2020-10-22 08:24
> I won't support adding different density images in the Resources folder since it is a deprecated way to deal with images.
Starting with iOS 9, you should use Asset Catalogs Image Sets:
https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=macos

> However I will add a configuration option to disable the handling of such source in the next version :)

**Comment by roubachof** [comment] 2020-10-22 10:11
Closing this one as duplicate of #13.

**Closed by roubachof** 2020-10-22 10:11 UTC
